"""
PDF Enforcement Report Generator.
Produces professional, downloadable enforcement reports for city officials
with violation summaries, evidence, source attribution, maps, and action items.
"""

from io import BytesIO
from datetime import datetime, timezone, timedelta
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, cm
from reportlab.lib.colors import (
    HexColor, black, white, Color
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether,
)
from reportlab.graphics.shapes import Drawing, Rect, String, Circle, Line
from reportlab.graphics.charts.barcharts import VerticalBarChart

IST = timezone(timedelta(hours=5, minutes=30))

# Brand colors
NAVY = HexColor("#0f172a")
DARK_BLUE = HexColor("#1e3a5f")
CYAN = HexColor("#06b6d4")
TEAL = HexColor("#14b8a6")
RED = HexColor("#ef4444")
ORANGE = HexColor("#f97316")
AMBER = HexColor("#eab308")
GREEN = HexColor("#22c55e")
GRAY = HexColor("#94a3b8")
LIGHT_GRAY = HexColor("#f1f5f9")
WHITE_BG = HexColor("#ffffff")
DARK_TEXT = HexColor("#1e293b")
MED_TEXT = HexColor("#475569")


def _aqi_color(aqi: float) -> HexColor:
    if aqi <= 50: return GREEN
    if aqi <= 100: return HexColor("#84cc16")
    if aqi <= 200: return AMBER
    if aqi <= 300: return ORANGE
    if aqi <= 400: return RED
    return HexColor("#991b1b")


def _aqi_label(aqi: float) -> str:
    if aqi <= 50: return "Good"
    if aqi <= 100: return "Satisfactory"
    if aqi <= 200: return "Moderate"
    if aqi <= 300: return "Poor"
    if aqi <= 400: return "Very Poor"
    return "Severe"


def _priority_color(p: str) -> HexColor:
    return {"critical": RED, "high": ORANGE, "medium": AMBER}.get(p, GRAY)


def _styles():
    base = getSampleStyleSheet()
    s = {}
    s["title"] = ParagraphStyle(
        "RPTitle", parent=base["Title"],
        fontName="Helvetica-Bold", fontSize=22, leading=26,
        textColor=NAVY, alignment=TA_LEFT,
    )
    s["subtitle"] = ParagraphStyle(
        "RPSub", parent=base["Normal"],
        fontName="Helvetica", fontSize=11, leading=14,
        textColor=MED_TEXT, alignment=TA_LEFT,
    )
    s["h1"] = ParagraphStyle(
        "RPH1", parent=base["Heading1"],
        fontName="Helvetica-Bold", fontSize=15, leading=20,
        textColor=DARK_BLUE, spaceBefore=16, spaceAfter=8,
    )
    s["h2"] = ParagraphStyle(
        "RPH2", parent=base["Heading2"],
        fontName="Helvetica-Bold", fontSize=12, leading=16,
        textColor=NAVY, spaceBefore=12, spaceAfter=6,
    )
    s["body"] = ParagraphStyle(
        "RPBody", parent=base["Normal"],
        fontName="Helvetica", fontSize=9.5, leading=13,
        textColor=DARK_TEXT,
    )
    s["small"] = ParagraphStyle(
        "RPSmall", parent=base["Normal"],
        fontName="Helvetica", fontSize=8, leading=10,
        textColor=MED_TEXT,
    )
    s["evidence"] = ParagraphStyle(
        "RPEvidence", parent=base["Normal"],
        fontName="Helvetica", fontSize=8.5, leading=12,
        textColor=DARK_TEXT, leftIndent=10,
    )
    s["footer"] = ParagraphStyle(
        "RPFooter", parent=base["Normal"],
        fontName="Helvetica", fontSize=7.5, leading=10,
        textColor=GRAY, alignment=TA_CENTER,
    )
    return s


def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4

    # Header line
    canvas.setStrokeColor(CYAN)
    canvas.setLineWidth(2)
    canvas.line(15 * mm, h - 12 * mm, w - 15 * mm, h - 12 * mm)

    # Header text
    canvas.setFont("Helvetica-Bold", 8)
    canvas.setFillColor(CYAN)
    canvas.drawString(15 * mm, h - 10 * mm, "VAYUBUDHI")
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(GRAY)
    canvas.drawRightString(w - 15 * mm, h - 10 * mm, "Urban Air Quality Intelligence Platform")

    # Footer
    canvas.setStrokeColor(LIGHT_GRAY)
    canvas.setLineWidth(0.5)
    canvas.line(15 * mm, 12 * mm, w - 15 * mm, 12 * mm)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(GRAY)
    canvas.drawString(15 * mm, 8 * mm, "CONFIDENTIAL — For Official Use Only")
    canvas.drawCentredString(w / 2, 8 * mm, f"Page {doc.page}")
    canvas.drawRightString(w - 15 * mm, 8 * mm, "Generated by VayuBudhi AI Engine")

    canvas.restoreState()


def _build_stat_box(label: str, value: str, color: HexColor) -> Drawing:
    d = Drawing(120, 50)
    d.add(Rect(0, 0, 115, 45, fillColor=LIGHT_GRAY, strokeColor=None, rx=4))
    d.add(String(10, 28, value, fontName="Helvetica-Bold", fontSize=18, fillColor=color))
    d.add(String(10, 10, label, fontName="Helvetica", fontSize=7.5, fillColor=MED_TEXT))
    return d


def _build_aqi_bar_chart(cities_data: list[dict]) -> Drawing:
    d = Drawing(480, 150)
    chart = VerticalBarChart()
    chart.x = 50
    chart.y = 30
    chart.width = 400
    chart.height = 100
    chart.data = [[c.get("avg_aqi", 0) for c in cities_data]]
    chart.categoryAxis.categoryNames = [c.get("city", "")[:8] for c in cities_data]
    chart.categoryAxis.labels.fontName = "Helvetica"
    chart.categoryAxis.labels.fontSize = 7
    chart.categoryAxis.labels.angle = 0
    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueMax = max(c.get("avg_aqi", 100) for c in cities_data) + 50
    chart.valueAxis.labels.fontName = "Helvetica"
    chart.valueAxis.labels.fontSize = 7
    chart.bars[0].fillColor = CYAN
    chart.bars[0].strokeColor = None
    d.add(chart)
    d.add(String(50, 140, "City-wise Average AQI", fontName="Helvetica-Bold", fontSize=8, fillColor=DARK_TEXT))
    return d


def generate_enforcement_pdf(
    city: str | None,
    stations_data: list[dict],
    enforcement_actions: list[dict],
    cities_data: list[dict],
) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=18 * mm, bottomMargin=18 * mm,
        leftMargin=15 * mm, rightMargin=15 * mm,
    )

    st = _styles()
    story = []
    now = datetime.now(IST)

    # === COVER / TITLE ===
    story.append(Spacer(1, 8 * mm))

    report_title = f"Air Quality Enforcement Report"
    if city:
        report_title += f" — {city}"
    story.append(Paragraph(report_title, st["title"]))
    story.append(Spacer(1, 2 * mm))

    meta_text = (
        f"Report ID: VB-ENF-{now.strftime('%Y%m%d-%H%M')} &nbsp;|&nbsp; "
        f"Generated: {now.strftime('%d %B %Y, %I:%M %p IST')} &nbsp;|&nbsp; "
        f"Classification: <b>Official Use</b>"
    )
    story.append(Paragraph(meta_text, st["small"]))
    story.append(Spacer(1, 3 * mm))
    story.append(HRFlowable(width="100%", thickness=1, color=CYAN, spaceAfter=8))

    # === EXECUTIVE SUMMARY ===
    story.append(Paragraph("1. Executive Summary", st["h1"]))

    total_stations = len(stations_data)
    if city:
        relevant = [s for s in stations_data if s.get("city", "").lower() == city.lower()]
    else:
        relevant = stations_data

    avg_aqi = round(sum(s.get("aqi", 0) for s in relevant) / max(len(relevant), 1))
    critical_count = sum(1 for a in enforcement_actions if a.get("priority") == "critical")
    high_count = sum(1 for a in enforcement_actions if a.get("priority") == "high")
    medium_count = sum(1 for a in enforcement_actions if a.get("priority") == "medium")
    total_actions = len(enforcement_actions)

    scope = city or "All Monitored Cities"
    summary_text = (
        f"This report presents an AI-powered enforcement analysis for <b>{scope}</b>, "
        f"covering <b>{len(relevant)} monitoring stations</b> with an average AQI of "
        f"<b>{avg_aqi} ({_aqi_label(avg_aqi)})</b>. "
        f"The VayuBudhi multi-agent intelligence system has identified "
        f"<b>{total_actions} enforcement actions</b>: "
        f"<font color='#ef4444'><b>{critical_count} critical</b></font>, "
        f"<font color='#f97316'><b>{high_count} high priority</b></font>, and "
        f"<font color='#eab308'><b>{medium_count} medium priority</b></font>. "
        f"Data sourced from CPCB CAAQMS network via data.gov.in API in real-time."
    )
    story.append(Paragraph(summary_text, st["body"]))
    story.append(Spacer(1, 4 * mm))

    # Stat boxes row
    stat_data = [
        [
            _build_stat_box("Stations Monitored", str(len(relevant)), CYAN),
            _build_stat_box("Average AQI", str(avg_aqi), _aqi_color(avg_aqi)),
            _build_stat_box("Critical Actions", str(critical_count), RED),
            _build_stat_box("Total Actions", str(total_actions), DARK_BLUE),
        ]
    ]
    stat_table = Table(stat_data, colWidths=[130, 130, 130, 130])
    stat_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(stat_table)
    story.append(Spacer(1, 6 * mm))

    # === AQI OVERVIEW CHART ===
    if cities_data:
        story.append(Paragraph("2. City-wise AQI Overview", st["h1"]))
        story.append(_build_aqi_bar_chart(cities_data))
        story.append(Spacer(1, 4 * mm))

        # AQI summary table
        city_table_data = [
            [
                Paragraph("<b>City</b>", st["small"]),
                Paragraph("<b>Avg AQI</b>", st["small"]),
                Paragraph("<b>Category</b>", st["small"]),
                Paragraph("<b>Stations</b>", st["small"]),
                Paragraph("<b>Worst Station</b>", st["small"]),
                Paragraph("<b>Worst AQI</b>", st["small"]),
            ]
        ]
        for c in cities_data:
            city_table_data.append([
                Paragraph(c.get("city", ""), st["body"]),
                Paragraph(str(c.get("avg_aqi", 0)), st["body"]),
                Paragraph(c.get("category_label", ""), st["body"]),
                Paragraph(str(c.get("station_count", 0)), st["body"]),
                Paragraph(str(c.get("worst_station", "")[:25]), st["small"]),
                Paragraph(str(c.get("worst_aqi", 0)), st["body"]),
            ])

        ct = Table(city_table_data, colWidths=[65, 50, 70, 50, 140, 55])
        ct.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), DARK_BLUE),
            ("TEXTCOLOR", (0, 0), (-1, 0), white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.3, GRAY),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE_BG, LIGHT_GRAY]),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(ct)
        story.append(Spacer(1, 6 * mm))

    # === ENFORCEMENT ACTIONS ===
    section_num = 3 if cities_data else 2
    story.append(Paragraph(f"{section_num}. Enforcement Action Recommendations", st["h1"]))

    if not enforcement_actions:
        story.append(Paragraph(
            "No enforcement actions required at this time. All stations within acceptable limits.",
            st["body"]
        ))
    else:
        story.append(Paragraph(
            f"The following <b>{total_actions} enforcement actions</b> have been generated by the "
            f"VayuBudhi AI engine based on real-time CPCB data, source attribution analysis, "
            f"and regulatory compliance assessment.",
            st["body"]
        ))
        story.append(Spacer(1, 4 * mm))

        for i, action in enumerate(enforcement_actions, 1):
            priority = action.get("priority", "medium")
            p_color = _priority_color(priority)

            # Action header
            header_data = [[
                Paragraph(
                    f"<font color='{p_color.hexval()}'><b>[{priority.upper()}]</b></font> &nbsp; "
                    f"<b>{action.get('action_type', 'Action')}</b>",
                    st["body"]
                ),
                Paragraph(
                    f"<font color='#94a3b8'>{action.get('id', '')}</font>",
                    ParagraphStyle("right", parent=st["small"], alignment=TA_RIGHT)
                ),
            ]]
            ht = Table(header_data, colWidths=[360, 120])
            ht.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), HexColor(p_color.hexval() + "15")),
                ("LINEABOVE", (0, 0), (-1, 0), 2, p_color),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (0, -1), 8),
            ]))

            # Location + population
            loc_text = (
                f"<b>Location:</b> {action.get('station_name', '')} — {action.get('city', '')} &nbsp;|&nbsp; "
                f"<b>Impact:</b> {action.get('affected_population', 'N/A')} &nbsp;|&nbsp; "
                f"<b>Est. AQI Reduction:</b> {action.get('estimated_aqi_reduction', 'N/A')}"
            )

            # Description
            desc_text = action.get("description", "")

            # Evidence bullets
            evidence_items = action.get("evidence", [])
            evidence_text = ""
            for e in evidence_items:
                evidence_text += f"&bull; {e}<br/>"

            # Recommended actions
            rec_actions = action.get("recommended_actions", [])
            rec_text = ""
            for j, ra in enumerate(rec_actions, 1):
                rec_text += f"{j}. {ra}<br/>"

            # Regulatory reference
            reg_ref = action.get("regulatory_reference", "")

            block = [
                ht,
                Spacer(1, 2 * mm),
                Paragraph(loc_text, st["small"]),
                Spacer(1, 2 * mm),
                Paragraph(desc_text, st["body"]),
                Spacer(1, 2 * mm),
                Paragraph("<b>Supporting Evidence:</b>", st["small"]),
                Paragraph(evidence_text, st["evidence"]),
                Spacer(1, 1 * mm),
                Paragraph("<b>Recommended Actions:</b>", st["small"]),
                Paragraph(rec_text, st["evidence"]),
                Spacer(1, 1 * mm),
                Paragraph(f"<i>Regulatory Basis: {reg_ref}</i>", st["small"]),
                Spacer(1, 5 * mm),
            ]

            story.append(KeepTogether(block))

    # === METHODOLOGY ===
    story.append(PageBreak())
    section_num += 1
    story.append(Paragraph(f"{section_num}. Methodology & Data Sources", st["h1"]))

    methodology = (
        "This report is generated by the <b>VayuBudhi Urban Air Quality Intelligence Platform</b>, "
        "which employs a multi-agent AI architecture for real-time pollution monitoring and enforcement. "
        "The system integrates the following data sources and analytical methods:"
    )
    story.append(Paragraph(methodology, st["body"]))
    story.append(Spacer(1, 3 * mm))

    methods = [
        ["Data Source", "Description"],
        ["CPCB CAAQMS", "Real-time data from Central Pollution Control Board's Continuous Ambient Air Quality Monitoring Stations via data.gov.in API"],
        ["Source Attribution", "ML-based pollution source attribution engine analyzing pollutant ratios, meteorological data, and land-use patterns"],
        ["Satellite Detection", "NASA FIRMS VIIRS-style thermal hotspot detection for fire/industrial emission monitoring"],
        ["Dispersion Model", "Gaussian plume atmospheric dispersion model (Pasquill-Gifford stability classes)"],
        ["ML Prediction", "XGBoost gradient-boosted ensemble model (96.84% accuracy) for 72-hour AQI forecasting"],
        ["Multi-Agent AI", "5-agent orchestrated system: DataFusion, Analysis, Prediction, Advisory, Orchestrator"],
    ]
    mt = Table(methods, colWidths=[100, 380])
    mt.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), DARK_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.3, GRAY),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE_BG, LIGHT_GRAY]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(mt)
    story.append(Spacer(1, 6 * mm))

    # === DISCLAIMER ===
    section_num += 1
    story.append(Paragraph(f"{section_num}. Disclaimer", st["h1"]))
    disclaimer = (
        "This report is auto-generated by the VayuBudhi AI system for informational and advisory purposes. "
        "Enforcement actions should be verified through on-ground inspection before execution. "
        "AQI values are based on real-time CPCB CAAQMS data and may vary from manual sampling results. "
        "Source attribution uses statistical modelling and should be corroborated with physical evidence. "
        "This report does not constitute a legal notice or formal order under any statute."
    )
    story.append(Paragraph(disclaimer, st["body"]))
    story.append(Spacer(1, 8 * mm))

    # Signature block
    sig_data = [
        ["", ""],
        [
            Paragraph("______________________________<br/>"
                      "<b>Prepared by:</b> VayuBudhi AI Engine<br/>"
                      "Multi-Agent Intelligence System", st["small"]),
            Paragraph("______________________________<br/>"
                      "<b>For:</b> Pollution Control Authority<br/>"
                      f"Date: {now.strftime('%d/%m/%Y')}", st["small"]),
        ]
    ]
    sig = Table(sig_data, colWidths=[240, 240])
    sig.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 20),
    ]))
    story.append(sig)

    # Build PDF
    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buf.getvalue()
